### ISSUE TITLE
How to recreate Fig 3 i.e. 2D loss surface plots for an entire training trajectory of a real model say 2 layer MLP/ResNet18

### ISSUE THREAD

**Issue by sanyalsunny111** [tml-epfl/sgd-sparse-features#1]
Hi @max-andr ,

This project looks really insightful and interesting. The current dia_2d_loss_surface.ipynb uses synthetic train and test update results. I would be very grateful if you may provide me with a colab to visualize 2D loss surface plots for a real model for instance a 2 layer MLP or ResNet-18. Thank you in advance.

**Comment by max-andr** [comment]
Hi @sanyalsunny111,

Thanks for the interest in our work. 

Unfortunately, I don't have a colab with visualizations of other models. But it should be relatively easy to implement it, you just need to regularly save checkpoints of two training runs (with a small and large step sizes).

Best,
Maksym

**Comment by max-andr** [comment]
closing it for now!
